# https://docs.docker.com/compose/compose-file

version: '3.1'

services:
  db:
    image: postgres:9.4
    container_name: db
    environment:
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
          - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
