# https://docs.docker.com/compose/compose-file

version: '3.1'

services:
  db:
    image: postgres:9.4
    container_name: db
    environment:
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
    volumes:
          - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
      - front-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: