CREATE TABLE USERS
(
  id         SERIAL PRIMARY KEY,
  username   VARCHAR(255) NOT NULL,
  first_name VARCHAR(500) NOT NULL,
  last_name  VARCHAR(500) NOT NULL,
  email      VARCHAR(254) NOT NULL
);

CREATE UNIQUE INDEX UQ_USERS_username ON USERS (username);

CREATE TABLE SKILLS
(
  id   SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE USER_SKILL_RATINGS
(
  id       SERIAL PRIMARY KEY,
  user_id  INT NOT NULL,
  skill_id INT NOT NULL,
  rating   INT NOT NULL,
  CONSTRAINT FK_USER_SKILL_RATING_USERS_id FOREIGN KEY (user_id) REFERENCES USERS (id),
  CONSTRAINT FK_USER_SKILL_RATING_SKILLS_id FOREIGN KEY (skill_id) REFERENCES SKILLS (id)
);

CREATE INDEX IX_USERS_SKILL_RATINGS_user_id ON USER_SKILL_RATING (user_id);
CREATE INDEX IX_USER_SKILL_RATING_skill_id ON USER_SKILL_RATING (skill_id);
